package com.jit.sensor.Mapper;

import com.jit.sensor.Entity.Devicedata;

public interface DevicedataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String deviceeui);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    int insert(Devicedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    int insertSelective(Devicedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    Devicedata selectByPrimaryKey(String deviceeui);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Devicedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table devicedata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Devicedata record);
}