package com.jit.sensor.mapper;

import com.jit.sensor.model.Sensorinfo;
import com.jit.sensor.model.SensorinfoKey;
import org.apache.ibatis.annotations.Param;

public interface SensorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SensorinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    int insert(Sensorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    int insertSelective(Sensorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    Sensorinfo selectByPrimaryKey(SensorinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sensorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensorinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sensorinfo record);

    Sensorinfo selectByNeedData(@Param("deveui") String deveui, @Param("devtype") String devtype);
}