package com.jit.sensor.mapper;

import com.jit.sensor.entity.Universaldata;
import com.jit.sensor.entity.UniversaldataKey;
import org.apache.ibatis.annotations.Param;

public interface UniversaldataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UniversaldataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    int insert(Universaldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    int insertSelective(Universaldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    Universaldata selectByPrimaryKey(UniversaldataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Universaldata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table universaldata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Universaldata record);

    Universaldata selectLastInfo(@Param("deveui")String deveui ,@Param("devtype") String devtype);
}