package com.jit.sensor.model;

public class SensorinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensorinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensorinfo.deveui
     *
     * @mbggenerated
     */
    private String deveui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensorinfo.devtype
     *
     * @mbggenerated
     */
    private String devtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensorinfo.id
     *
     * @return the value of sensorinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensorinfo.id
     *
     * @param id the value for sensorinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensorinfo.deveui
     *
     * @return the value of sensorinfo.deveui
     *
     * @mbggenerated
     */
    public String getDeveui() {
        return deveui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensorinfo.deveui
     *
     * @param deveui the value for sensorinfo.deveui
     *
     * @mbggenerated
     */
    public void setDeveui(String deveui) {
        this.deveui = deveui == null ? null : deveui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensorinfo.devtype
     *
     * @return the value of sensorinfo.devtype
     *
     * @mbggenerated
     */
    public String getDevtype() {
        return devtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensorinfo.devtype
     *
     * @param devtype the value for sensorinfo.devtype
     *
     * @mbggenerated
     */
    public void setDevtype(String devtype) {
        this.devtype = devtype == null ? null : devtype.trim();
    }
}