package com.jit.sensor.model;

public class Sensordata extends SensordataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensordata.windspeed
     *
     * @mbggenerated
     */
    private Double windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensordata.temp
     *
     * @mbggenerated
     */
    private Double temp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensordata.humidity
     *
     * @mbggenerated
     */
    private Double humidity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensordata.windspeed
     *
     * @return the value of sensordata.windspeed
     *
     * @mbggenerated
     */
    public Double getWindspeed() {
        return windspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensordata.windspeed
     *
     * @param windspeed the value for sensordata.windspeed
     *
     * @mbggenerated
     */
    public void setWindspeed(Double windspeed) {
        this.windspeed = windspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensordata.temp
     *
     * @return the value of sensordata.temp
     *
     * @mbggenerated
     */
    public Double getTemp() {
        return temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensordata.temp
     *
     * @param temp the value for sensordata.temp
     *
     * @mbggenerated
     */
    public void setTemp(Double temp) {
        this.temp = temp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensordata.humidity
     *
     * @return the value of sensordata.humidity
     *
     * @mbggenerated
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensordata.humidity
     *
     * @param humidity the value for sensordata.humidity
     *
     * @mbggenerated
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }
}