package com.jit.sensor.entity;

public class Devicedata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicedata.deviceEUI
     *
     * @mbggenerated
     */
    private String deviceeui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicedata.applicationName
     *
     * @mbggenerated
     */
    private String applicationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column devicedata.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicedata.deviceEUI
     *
     * @return the value of devicedata.deviceEUI
     *
     * @mbggenerated
     */
    public String getDeviceeui() {
        return deviceeui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicedata.deviceEUI
     *
     * @param deviceeui the value for devicedata.deviceEUI
     *
     * @mbggenerated
     */
    public void setDeviceeui(String deviceeui) {
        this.deviceeui = deviceeui == null ? null : deviceeui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicedata.applicationName
     *
     * @return the value of devicedata.applicationName
     *
     * @mbggenerated
     */
    public String getApplicationname() {
        return applicationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicedata.applicationName
     *
     * @param applicationname the value for devicedata.applicationName
     *
     * @mbggenerated
     */
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname == null ? null : applicationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column devicedata.data
     *
     * @return the value of devicedata.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column devicedata.data
     *
     * @param data the value for devicedata.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}