package com.jit.sensor.Entity;

public class Sensorinfo extends SensorinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensorinfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensorinfo.datalength
     *
     * @mbggenerated
     */
    private String datalength;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensorinfo.name
     *
     * @return the value of sensorinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensorinfo.name
     *
     * @param name the value for sensorinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensorinfo.datalength
     *
     * @return the value of sensorinfo.datalength
     *
     * @mbggenerated
     */
    public String getDatalength() {
        return datalength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensorinfo.datalength
     *
     * @param datalength the value for sensorinfo.datalength
     *
     * @mbggenerated
     */
    public void setDatalength(String datalength) {
        this.datalength = datalength == null ? null : datalength.trim();
    }

    @Override
    public String toString() {
        return "Sensorinfo{" +
                "name='" + name + '\'' +
                ", datalength='" + datalength + '\'' +
                '}';
    }
}