package com.jit.sensor.entity;

import javax.persistence.Entity;

@Entity
public class Universaldata extends UniversaldataKey {
    @Override
    public String toString() {
        return "Universaldata{" +
                "data='" + data + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column universaldata.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column universaldata.data
     *
     * @return the value of universaldata.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column universaldata.data
     *
     * @param data the value for universaldata.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}