package com.jit.sensor.Entity;

public class UniversaldataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column universaldata.deveui
     *
     * @mbggenerated
     */
    private String deveui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column universaldata.devtype
     *
     * @mbggenerated
     */
    private String devtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column universaldata.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column universaldata.deveui
     *
     * @return the value of universaldata.deveui
     *
     * @mbggenerated
     */
    public String getDeveui() {
        return deveui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column universaldata.deveui
     *
     * @param deveui the value for universaldata.deveui
     *
     * @mbggenerated
     */
    public void setDeveui(String deveui) {
        this.deveui = deveui == null ? null : deveui.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column universaldata.devtype
     *
     * @return the value of universaldata.devtype
     *
     * @mbggenerated
     */
    public String getDevtype() {
        return devtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column universaldata.devtype
     *
     * @param devtype the value for universaldata.devtype
     *
     * @mbggenerated
     */
    public void setDevtype(String devtype) {
        this.devtype = devtype == null ? null : devtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column universaldata.time
     *
     * @return the value of universaldata.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column universaldata.time
     *
     * @param time the value for universaldata.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}